### ISSUE TITLE
运行直接崩

### ISSUE THREAD

**Issue by yxiangTang** [JsonChao/Awesome-WanAndroid#116]
2020-06-23 20:02:22.399 17374-17374/json.chao.com.wanandroid I/DexposedBridge: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/json.chao.com.wanandroid-n9olvVXRhTbyQjpfbsMVGQ==/base.apk"],nativeLibraryDirectories=[/data/app/json.chao.com.wanandroid-n9olvVXRhTbyQjpfbsMVGQ==/lib/arm, /data/app/json.chao.com.wanandroid-n9olvVXRhTbyQjpfbsMVGQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]] couldn't find "libdexposed.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.taobao.android.dexposed.DexposedBridge.<clinit>(DexposedBridge.java:59)
        at com.taobao.android.dexposed.DexposedBridge.hookAllConstructors(DexposedBridge.java:201)
        at json.chao.com.wanandroid.app.WanAndroidApp.onCreate(WanAndroidApp.java:147)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1204)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6648)
        at android.app.ActivityThread.access$1600(ActivityThread.java:232)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1953)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by ydslib** [comment]
一样的，
手机：红米5note android9.0
I/DexposedBridge: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/json.chao.com.wanandroid-6MS8Q5JV3PutXnb8WnsHFA==/base.apk"],nativeLibraryDirectories=[/data/app/json.chao.com.wanandroid-6MS8Q5JV3PutXnb8WnsHFA==/lib/arm, /data/app/json.chao.com.wanandroid-6MS8Q5JV3PutXnb8WnsHFA==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find "libdexposed.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.taobao.android.dexposed.DexposedBridge.<clinit>(DexposedBridge.java:59)
        at com.taobao.android.dexposed.DexposedBridge.hookAllConstructors(DexposedBridge.java:201)
        at json.chao.com.wanandroid.app.WanAndroidApp.onCreate(WanAndroidApp.java:147)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5949)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
