### ISSUE TITLE
第一次运行项目时点击run 可以build但是不能安装到手机上 所以我使用的是adb安装  adb安装没问题 但是安装完打开APP出现崩溃 打印出的log日志如下  我使用的是vivo  iqoo neo 855

### ISSUE THREAD

**Issue by douhaopeng** [JsonChao/Awesome-WanAndroid#125]
2021-06-10 14:51:45.908 24900-24900/? I/.com.wanandroi: Late-enabling -Xcheck:jni
2021-06-10 14:51:45.921 24900-24900/? I/.com.wanandroi: Unquickening 24 vdex files!
2021-06-10 14:51:45.922 24900-24900/? W/.com.wanandroi: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
2021-06-10 14:51:45.962 24900-24900/json.chao.com.wanandroid D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2021-06-10 14:51:45.963 24900-24900/json.chao.com.wanandroid I/.com.wanandroi: The ClassLoaderContext is a special shared library.
2021-06-10 14:51:46.225 24900-24900/json.chao.com.wanandroid D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-06-10 14:51:46.226 24900-24900/json.chao.com.wanandroid D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-06-10 14:51:46.235 24900-24900/json.chao.com.wanandroid I/MultiDex: VM with version 2.1.0 has multidex support
2021-06-10 14:51:46.235 24900-24900/json.chao.com.wanandroid I/MultiDex: Installing application
2021-06-10 14:51:46.235 24900-24900/json.chao.com.wanandroid I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2021-06-10 14:51:46.236 24900-24900/json.chao.com.wanandroid D/AndroidRuntime: Shutting down VM
2021-06-10 14:51:46.237 24900-24900/json.chao.com.wanandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: json.chao.com.wanandroid, PID: 24900
    java.lang.RuntimeException: Unable to get provider com.tencent.bugly.beta.utils.BuglyFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.tencent.bugly.beta.utils.BuglyFileProvider" on path: DexPathList[[zip file "/data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/lib/arm, /data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7794)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7300)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7200)
        at android.app.ActivityThread.access$1500(ActivityThread.java:269)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:239)
        at android.app.ActivityThread.main(ActivityThread.java:8209)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.bugly.beta.utils.BuglyFileProvider" on path: DexPathList[[zip file "/data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/lib/arm, /data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7778)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7300) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7200) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:269) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:239) 
        at android.app.ActivityThread.main(ActivityThread.java:8209) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/FileProvider;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 13 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/lib/arm, /data/app/~~piHW0CRWI7REGgHCsGoddw==/json.chao.com.wanandroid-CZYNCUxPpNd6oGyN95b2JQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 16 more
2021-06-10 14:51:46.250 24900-24900/json.chao.com.wanandroid I/Process: Sending signal. PID: 24900 SIG: 9

**Comment by douhaopeng** [comment]
已经解决这个问题 需要把腾讯的bugly插件改一下版本 不用最新的版本就可以   该版本的地址如下https://bugly.qq.com/docs/release-notes/release-android-beta/?v=20200622202242  希望能够帮助到大家  瑞思拜！
