### ISSUE TITLE
版本适配问题，运行在8.0手机上直接崩溃

### ISSUE THREAD

**Issue by Sun0630** [JsonChao/Awesome-WanAndroid#37]
Process: json.chao.com.wanandroid, PID: 28737
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{json.chao.com.wanandroid/json.chao.com.wanandroid.ui.main.activity.SplashActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                              at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                           Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                                              at android.app.Activity.onCreate(Activity.java:986)
                                                                              at android.support.v4.app.BaseFragmentActivityGingerbread.onCreate(BaseFragmentActivityGingerbread.java:54)
                                                                              at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:319)
                                                                              at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
                                                                              at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
                                                                              at json.chao.com.wanandroid.base.activity.AbstractSimpleActivity.onCreate(AbstractSimpleActivity.java:25)
                                                                              at json.chao.com.wanandroid.base.activity.BaseActivity.onCreate(BaseActivity.java:37)
                                                                              at android.app.Activity.performCreate(Activity.java:6975)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)

把版本降为26正常

**Comment by JsonChao** [comment]
Thanks your issue, 已解决，请pull最新代码~
