### ISSUE TITLE
我运行咋报I/O exception during makeDexElement这个错误啊

### ISSUE THREAD

**Issue by shinelyme** [JsonChao/Awesome-WanAndroid#44]
Unable to extract+optimize DEX from '/data/data/json.chao.com.wanandroid/code_cache/secondary-dexes/json.chao.com.wanandroid-1.apk.classes2.zip'
07-19 11:40:54.248 19229-19229/json.chao.com.wanandroid E/MultiDex: MultiDex installation failure
                                                                    java.io.IOException: I/O exception during makeDexElement
                                                                        at android.support.multidex.MultiDex$V19.install(MultiDex.java:541)
                                                                        at android.support.multidex.MultiDex.installSecondaryDexes(MultiDex.java:347)
                                                                        at android.support.multidex.MultiDex.doInstallation(MultiDex.java:272)
                                                                        at android.support.multidex.MultiDex.install(MultiDex.java:112)
                                                                        at json.chao.com.wanandroid.app.WanAndroidApp.attachBaseContext(WanAndroidApp.java:84)
                                                                        at android.app.Application.attach(Application.java:201)
                                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:998)
                                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                                        at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569)
                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: java.io.IOException: unable to open DEX file
                                                                        at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                        at dalvik.system.DexFile.openDexFile(DexFile.java:296)
                                                                        at dalvik.system.DexFile.<init>(DexFile.java:111)
                                                                        at dalvik.system.DexFile.loadDex(DexFile.java:151)
                                                                        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:266)
                                                                        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:230)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at android.support.multidex.MultiDex$V19.makeDexElements(MultiDex.java:560)
                                                                        at android.support.multidex.MultiDex$V19.install(MultiDex.java:513)
                                                                        at android.support.multidex.MultiDex.installSecondaryDexes(MultiDex.java:347) 
                                                                        at android.support.multidex.MultiDex.doInstallation(MultiDex.java:272) 
                                                                        at android.support.multidex.MultiDex.install(MultiDex.java:112) 
                                                                        at json.chao.com.wanandroid.app.WanAndroidApp.attachBaseContext(WanAndroidApp.java:84) 
                                                                        at android.app.Application.attach(Application.java:201) 
                                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:998) 
                                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                                        at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569) 
                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:136) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5433) 
                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                        at dalvik.system.NativeStart.main(Native Method) 
07-19 11:40:54.258 19229-19229/json.chao.com.wanandroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: json.chao.com.wanandroid, PID: 19229
                                                                          java.lang.RuntimeException: Unable to instantiate application json.chao.com.wanandroid.app.WanAndroidApp: java.lang.RuntimeException: MultiDex installation failed (I/O exception during makeDexElement).
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569)
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: java.lang.RuntimeException: MultiDex installation failed (I/O exception during makeDexElement).
                                                                              at android.support.multidex.MultiDex.install(MultiDex.java:121)
                                                                              at json.chao.com.wanandroid.app.WanAndroidApp.attachBaseContext(WanAndroidApp.java:84)
                                                                              at android.app.Application.attach(Application.java:201)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:998)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569) 
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:136) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5433) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by JsonChao** [comment]
Thank your issue，确认下是否是最新代码，项目中的mutildex设置相关部分是否被改动，如果都正常的话，考虑是机型Rom定制化，从而导致mutildex失效的原因~
