### ISSUE TITLE
Android P运行闪退

### ISSUE THREAD

**Issue by Sencer97** [JsonChao/Awesome-WanAndroid#64]
测试机型小米 8 （Android P），报错如下：
android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader
Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:651)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.

**Comment by songmao123** [comment]
Pixel2 也是打开就崩:
```java
2018-10-06 16:15:27.904 3707-3707/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: json.chao.com.wanandroid, PID: 3707
    android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader
    Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at json.chao.com.wanandroid.base.AbstractSimpleFragment.onCreateView(AbstractSimpleFragment.java:31)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
        at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
        at android.view.View.measure(View.java:23169)
        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
```
