### ISSUE TITLE
Google pixel Android8.1.0系统

### ISSUE THREAD

**Issue by PrettysBoy** [JsonChao/Awesome-WanAndroid#81]
json.chao.com.wanandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: json.chao.com.wanandroid, PID: 16856
    java.lang.RuntimeException: Unable to start activity ComponentInfo{json.chao.com.wanandroid/json.chao.com.wanandroid.ui.main.activity.ArticleDetailActivity}: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
     Caused by: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:213)
        at android.webkit.WebView.getFactory(WebView.java:2530)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2525)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2590)
        at android.view.View.<init>(View.java:4574)
        at android.view.View.<init>(View.java:4706)
        at android.view.ViewGroup.<init>(ViewGroup.java:597)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
        at android.webkit.WebView.<init>(WebView.java:643)
        at android.webkit.WebView.<init>(WebView.java:588)
        at android.webkit.WebView.<init>(WebView.java:571)
        at android.webkit.WebView.<init>(WebView.java:558)
        at android.webkit.WebView.<init>(WebView.java:548)
        at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:240)
        at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:181)
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:157)
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34)
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:197)
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43)
        at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:567)
        at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:499)
        at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:706)
        at json.chao.com.wanandroid.ui.main.activity.ArticleDetailActivity.initEventAndData(ArticleDetailActivity.java:102)
        at json.chao.com.wanandroid.base.activity.AbstractSimpleActivity.onCreate(AbstractSimpleActivity.java:36)
        at json.chao.com.wanandroid.base.activity.BaseActivity.onCreate(BaseActivity.java:37)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:208)
        at android.webkit.WebView.getFactory(WebView.java:2530) 
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2525) 
        at android.webkit.WebView.setOverScrollMode(WebView.java:2590) 
        at android.view.View.<init>(View.java:4574) 
        at android.view.View.<init>(View.java:4706) 
        at android.view.ViewGroup.<init>(ViewGroup.java:597) 
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55) 
        at android.webkit.WebView.<init>(WebView.java:643) 
        at android.webkit.WebView.<init>(WebView.java:588) 
        at android.webkit.WebView.<init>(WebView.java:571) 
        at android.webkit.WebView.<init>(WebView.java:558) 
        at android.webkit.WebView.<init>(WebView.java:548) 
        at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:240) 
        at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:181) 
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:157) 
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34) 
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:197) 
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43) 
        at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:567) 
        at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:499) 
        at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:706) 
        at json.chao.com.wanandroid.ui.main.activity.ArticleDetailActivity.initEventAndData(ArticleDetailActivity.java:102) 
        at json.chao.com.wanandroid.base.activity.AbstractSimpleActivity.onCreate(AbstractSimpleActivity.java:36) 
        at json.chao.com.wanandroid.base.activity.BaseActivity.onCreate(BaseActivity.java:37) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108) 
     Caused by: java.lang.RuntimeException: Cannot load WebView
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(SourceFile:118)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(SourceFile:32)
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1.<init>(SourceFile:2)
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1.create(SourceFile:1)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:208) 
        at android.webkit.WebView.getFactory(WebView.java:2530) 
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2525) 
        at android.webkit.WebView.setOverScrollMode(WebView.java:2590) 
        at android.view.View.<init>(View.java:4574) 
        at android.view.View.<init>(View.java:4706) 
        at android.view.ViewGroup.<init>(ViewGroup.java:597) 
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55) 
        at android.webkit.WebView.<init>(WebView.java:643) 
        at android.webkit.WebView.<init>(WebView.java:588) 
        at android.webkit.WebView.<init>(WebView.java:571) 
        at android.webkit.WebView.<init>(WebView.java:558) 
        at android.webkit.WebView.<init>(WebView.java:548) 
        at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:240) 
        at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:181) 
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:157) 
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34) 
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:197) 
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43) 
        at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:567) 
        at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:499) 
        at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:706) 
        at json.chao.com.wanandroid.ui.main.activity.ArticleDetailActivity.initEventAndData(ArticleDetailActivity.java:102) 
        at json.chao.com.wanandroid.base.activity.AbstractSimpleActivity.onCreate(AbstractSimpleActivity.java:36) 
        at json.chao.com.wanandroid.base.activity.BaseActivity.onCreate(BaseActivity.java:37) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108) 
     Caused by: aBo
        at org.chromium.base.library_loader.LibraryLoader.c(SourceFile:83)
        at org.chromium.base.library_loader.LibraryLoader.b(SourceFile:34)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(SourceFile:109)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(SourceFile:32) 
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1.<init>(SourceFile:2) 
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1.create(SourceFile:1) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:208) 
        at android.webkit.WebView.getFactory(WebView.java:2530) 
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2525) 
        at android.webkit.WebView.setOverScrollMode(WebView.java:2590) 
        at android.view.View.<init>(View.java:4574) 
        at android.view.View.<init>(View.java:4706) 
        at android.view.ViewGroup.<init>(ViewGroup.java:597) 
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55) 
        at android.webkit.WebView.<init>(WebView.java:643) 
        at android.webkit.WebView.<init>(WebView.java:588) 
        at android.webkit.WebView.<init>(WebView.java:571) 
        at android.webkit.WebView.<init>(WebView.java:558) 
        at android.webkit.WebView.<init>(WebView.java:548) 
        at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:240) 
        at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:181) 
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:157) 
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34) 
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:197) 
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43) 
        at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:567) 
        at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:499) 
        at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:706) 
        at json.chao.com.wanandroid.ui.main.activity.ArticleDetailActivity.initEventAndData(ArticleDetailActivity.java:102) 
        at json.chao.com.wanandroid.base.activity.AbstractSimpleActivity.onCreate(AbstractSimpleActivity.java:36) 
        at json.chao.com.wanandroid.base.activity.BaseActivity.onCreate(BaseActivity.java:37) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108) 
2019-02-15 14:55:00.712 16856-16856/json.chao.com.wanandroid E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.chrome-rWrt9YG8snV4TOSTXCUHBw==/base.apk!/lib/armeabi-v7a/libmonochrome.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at org.chromium.base.library_loader.LibraryLoader.c(SourceFile:65)
        	... 45 more

**Comment by JsonChao** [comment]
Thank your issue，这个是AgentWebView控件的兼容性问题，它没有加兼容Google pixel Android8.1.0系统，将它升级为最新版本应该可以解决。
