### ISSUE TITLE
运行后进入主界面闪退问题

### ISSUE THREAD

**Issue by sh1018727638** [JsonChao/Awesome-WanAndroid#85]
机型：HUAWEI Mate20 pro
系统：9.0
问题出现情况：必现

2019-03-11 14:17:46.269 925-925/json.chao.com.wanandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: json.chao.com.wanandroid, PID: 925
    android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader
    Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:658)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at json.chao.com.wanandroid.base.fragment.AbstractSimpleFragment.onCreateView(AbstractSimpleFragment.java:35)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
        at android.app.Activity.performStart(Activity.java:7457)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3324)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:278)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.ArithmeticException: divide by zero
        at com.scwang.smartrefresh.header.PhoenixHeader.setupPathsDrawable(PhoenixHeader.java:185)
        at com.scwang.smartrefresh.header.PhoenixHeader.initView(PhoenixHeader.java:140)
        at com.scwang.smartrefresh.header.PhoenixHeader.<init>(PhoenixHeader.java:121)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:658) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at json.chao.com.wanandroid.base.fragment.AbstractSimpleFragment.onCreateView(AbstractSimpleFragment.java:35) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149) 
        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013) 
        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419) 
        at android.app.Activity.performStart(Activity.java:7457) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3324) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:278) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by sh1018727638** [comment]
同样在HUAWEI Mate20上也尝试了一下，出现相同的错误。
