### ISSUE TITLE
WanAndroid客户端在小米8崩溃

### ISSUE THREAD

**Issue by CocoQueen** [JsonChao/Awesome-WanAndroid#87]
https://www.wanandroid.com/blog/show/2075 这个网址中的apk安装在小米8手机时，会报如下错误：

2019-03-12 16:56:53.333 20307-20307/? E/AndroidRuntime: FATAL EXCEPTION: main Process: json.chao.com.wanandroid, PID: 20307 android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader Caused by: java.lang.reflect.InvocationTargetException at java.lang.reflect.Constructor.newInstance0(Native Method) at java.lang.reflect.Constructor.newInstance(Constructor.java:343) at android.view.LayoutInflater.createView(LayoutInflater.java:651) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734) at android.view.LayoutInflater.rInflate(LayoutInflater.java:867) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) at android.view.LayoutInflater.inflate(LayoutInflater.java:519) at android.view.LayoutInflater.inflate(LayoutInflater.java:427) at json.chao.com.wanandroid.base.AbstractSimpleFragment.onCreateView(AbstractSimpleFragment.java:31) at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758) at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363) at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149) at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103) at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984) at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626) at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143) at android.support.v4.view.ViewPager.populate(ViewPager.java:1268) at android.support.v4.view.ViewPager.populate(ViewPager.java:1116) at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642) at android.view.View.measure(View.java:23223) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753) at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714) at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90) at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391) at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784) at android.view.View.measure(View.java:23223) at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081) at android.view.View.measure(View.java:23223) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753) at android.widget.FrameLayout.onMeasure(FrameLayout.java:185) at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139) at android.view.View.measure(View.java:23223) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753) at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535) at android.widget.LinearLayout.measureVertical(LinearLayout.java:825) at android.widget.LinearLayout.onMeasure(LinearLayout.java:704) at android.view.View.measure(View.java:23223) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753) at android.widget.FrameLayout.onMeasure(FrameLayout.java:185) at android.view.View.measure(View.java:23223) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753) at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535) at android.widget.LinearLayout.measureVertical(LinearLayout.java:825) 2019-03-12 16:56:53.333 20307-20307/? E/AndroidRuntime: at android.widget.LinearLayout.onMeasure(LinearLayout.java:704) at android.view.View.measure(View.java:23223) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753) at android.widget.FrameLayout.onMeasure(FrameLayout.java:185) at com.android.internal.policy.DecorView.onMeasure(DecorView.java:737) at android.view.View.measure(View.java:23223) at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2782) at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1635) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1919) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1523) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7395) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065) at android.view.Choreographer.doCallbacks(Choreographer.java:877) at android.view.Choreographer.doFrame(Choreographer.java:808) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:201) at android.app.ActivityThread.main(ActivityThread.java:6806) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) Caused by: java.lang.ArithmeticException: divide by zero at com.scwang.smartrefresh.header.PhoenixHeader.setupPathsDrawable(PhoenixHeader.java:185) at com.scwang.smartrefresh.header.PhoenixHeader.initView(PhoenixHeader.java:140) at com.scwang.smartrefresh.header.PhoenixHeader.<init>(PhoenixHeader.java:121) ... 70 more

**Comment by CocoQueen** [comment]
1、Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.scwang.smartrefresh.header.PhoenixHeader

2、Caused by: java.lang.ArithmeticException: divide by zero

**Comment by JsonChao** [comment]
Thank your issue，这个是最老的版本了，其中使用的第三方库存在一些兼容性的bug，请在现在的github md文件中扫描最新的二维码下载即可~
